### ISSUE TITLE
Non-static method

### ISSUE THREAD

**Issue by niqs87** [VizuaaLOG/laravel-recaptcha#1]
i try to use but,

Non-static method VizuaaLOG\Recaptcha\Recaptcha::check() should not be called statically, assuming $this from incompatible context

any idea?

or check($request) give me null

**Comment by VizuaaLOG** [comment]
In the PHP script you are using, did you add `use Recaptcha;` to the top? For example
```PHP
<?php

namespace App\Http\Controllers;

use Recaptcha;
use App\Http\Controllers\Controller;

class MyController extends Controller {
    public function index(Request $request)
    {
        if(Recaptcha::check($request)) {
            // Passed
        } else {
            // Failed
        }
    }
}
```

Looking at the readme this is something I should add :).

**Comment by niqs87** [comment]
In my case the problem was curl timeout, but thank you for your fast reply. topic to close.
